CREATE USER CDP IDENTIFIED BY afpa2016;

GRANT CREATE SESSION to CDP;
GRANT SELECT, INSERT, UPDATE ON RENAUD.PROJET TO CDP;
GRANT SELECT, INSERT, UPDATE ON RENAUD.ETAPE TO CDP;
GRANT SELECT, INSERT, UPDATE ON RENAUD.INTERVENTION TO CDP;
GRANT SELECT, INSERT, UPDATE ON RENAUD.TYPE_TECHNO TO CDP;
GRANT SELECT, INSERT, UPDATE ON RENAUD.TYPE_PROJET TO CDP;
GRANT SELECT, INSERT, UPDATE ON RENAUD.ACTIVITE TO CDP;
GRANT SELECT, INSERT, UPDATE ON RENAUD.DOCUMENT TO CDP;
GRANT SELECT, INSERT, UPDATE ON RENAUD.TECHNOLOGIE TO CDP;
GRANT SELECT ON RENAUD.COLLABORATEUR TO CDP;
