INSERT INTO ACTIVITE (ACTIVITE_ID, ACTIVITE_LIBELLE) VALUES (1, 'Secteur financier et juridique');
INSERT INTO ACTIVITE (ACTIVITE_ID, ACTIVITE_LIBELLE) VALUES (2, 'Négoce et commerce de biens');
INSERT INTO ACTIVITE (ACTIVITE_ID, ACTIVITE_LIBELLE) VALUES (3, 'Alimentation');
INSERT INTO ACTIVITE (ACTIVITE_ID, ACTIVITE_LIBELLE) VALUES (4, 'Bâtiment, Immobilier');
INSERT INTO ACTIVITE (ACTIVITE_ID, ACTIVITE_LIBELLE) VALUES (5, 'Expertise');
INSERT INTO ACTIVITE (ACTIVITE_ID, ACTIVITE_LIBELLE) VALUES (6, 'Tourisme, loisirs, culture');
INSERT INTO ACTIVITE (ACTIVITE_ID, ACTIVITE_LIBELLE) VALUES (7, 'Enseignement');
INSERT INTO ACTIVITE (ACTIVITE_ID, ACTIVITE_LIBELLE) VALUES (8, 'Autres services');
