INSERT INTO NATURE_CLIENT (NATURE_ID, NATURE_LIBELLE) VALUES (1,'principale');
INSERT INTO NATURE_CLIENT (NATURE_ID, NATURE_LIBELLE) VALUES (2,'secondaire');
INSERT INTO NATURE_CLIENT (NATURE_ID, NATURE_LIBELLE) VALUES (3,'ancienne');
