INSERT INTO TECHNOLOGIE (TECHNOLOGIE_ID, TYPETECHNO_ID, TECHNOLOGIE_LIBELLE) VALUES (1, 1,'Java');
INSERT INTO TECHNOLOGIE (TECHNOLOGIE_ID, TYPETECHNO_ID, TECHNOLOGIE_LIBELLE) VALUES (2, 1,'C#');
INSERT INTO TECHNOLOGIE (TECHNOLOGIE_ID, TYPETECHNO_ID, TECHNOLOGIE_LIBELLE) VALUES (3, 1,'PHP');
INSERT INTO TECHNOLOGIE (TECHNOLOGIE_ID, TYPETECHNO_ID, TECHNOLOGIE_LIBELLE) VALUES (4, 1,'Java EE');
INSERT INTO TECHNOLOGIE (TECHNOLOGIE_ID, TYPETECHNO_ID, TECHNOLOGIE_LIBELLE) VALUES (5, 2,'Oracle');
INSERT INTO TECHNOLOGIE (TECHNOLOGIE_ID, TYPETECHNO_ID, TECHNOLOGIE_LIBELLE) VALUES (6, 2,'mySQL');
INSERT INTO TECHNOLOGIE (TECHNOLOGIE_ID, TYPETECHNO_ID, TECHNOLOGIE_LIBELLE) VALUES (7, 3,'Ubuntu 16.04');
INSERT INTO TECHNOLOGIE (TECHNOLOGIE_ID, TYPETECHNO_ID, TECHNOLOGIE_LIBELLE) VALUES (8, 3,'Windows 10');
