INSERT INTO TYPE_PROJET(TYPEPROJ_ID,TYPEPROJ_LIBELLE) VALUES(1, 'forfait');
INSERT INTO TYPE_PROJET(TYPEPROJ_ID,TYPEPROJ_LIBELLE) VALUES(2, 'régie');
INSERT INTO TYPE_PROJET(TYPEPROJ_ID,TYPEPROJ_LIBELLE) VALUES(3, 'assistance');
