INSERT INTO GERE (CLIENT_ID, CONTACT_ID, PROJET_ID) VALUES (1,4,1601);
INSERT INTO GERE (CLIENT_ID, CONTACT_ID, PROJET_ID) VALUES (1,1,1602);
INSERT INTO GERE (CLIENT_ID, CONTACT_ID, PROJET_ID) VALUES (22,52,1603);
INSERT INTO GERE (CLIENT_ID, CONTACT_ID, PROJET_ID) VALUES (11,12,1604);
INSERT INTO GERE (CLIENT_ID, CONTACT_ID, PROJET_ID) VALUES (40,74,1605);
