CREATE USER SECRETAIRE IDENTIFIED BY afpa2016;

GRANT SELECT, CREATE SESSION ON RENAUD.PROJET TO SECRETAIRE;
GRANT INSERT, UPDATE (PROJET_DATE_REELLE_DEBUT, PROJET_DATE_REELLE_FIN, PROJET_COLLA_MAX) ON RENAUD.PROJET TO SECRETAIRE;
