INSERT INTO TYPE_TECHNO (TYPETECHNO_ID, TYPETECHNO_LIBELLE) VALUES (1, 'Langage');
INSERT INTO TYPE_TECHNO (TYPETECHNO_ID, TYPETECHNO_LIBELLE) VALUES (2, 'Base de donnée');
INSERT INTO TYPE_TECHNO (TYPETECHNO_ID, TYPETECHNO_LIBELLE) VALUES (3, 'Plateformes');
